project:
  type: website
  output-dir: docs

website:
  title: ""
  twitter-card: 
    site: "@DeshpandePia"
  sidebar:
    collapse-level: 1
    style: "docked"    
    search: false
    background: light
    foreground: dark
    tools:
      - icon: twitter
        href: https://x.com/deshpandepia
      - icon: envelope-at-fill
        href: mailto:pia_deshpande@berkeley.edu
      - icon: github
        href: https://github.com/pdeshlab
    contents:
      - text: "research"
        href: research.qmd
      - text: "teaching"
        href: teaching.qmd
      - text: "cv"
        href: CV.qmd
      - text: "data"
        href: data.qmd
      - section: "tutorials"
        contents:
          - text: "Plotting trends over time with the CES"
            href: tutorial2.qmd
          - text: "Introduction to functions in R"
            href: tutorial1.qmd
          - text: "Making maps with the CES"
            href: tutorial3.qmd
          
editor: source

